login1/login1/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from login1app import views

urlpatterns = [
    url(r'^$',views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^base/',include('login1app.urls')),
    url(r'^logout/$',views.user_logout,name='user_logout'),
    url(r'^special/',views.special,name='special'),
    url(r'^login/$',views.user_logout,name='user_login')
]

login1/login1app/urls.py
from django.conf.urls import url
from login1app import views

app_name='login1app'

urlpatterns=[
 url(r'^regi/$',views.register,name='register'),

]

login1/login1app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,)
    port = models.URLField(blank=True)
    profi = models.ImageField(upload_to='thepictures',blank=True)
    def __str__(self):
        return self.user.username

login1/login1app/forms.py
from django import forms
from django.contrib.auth.models import User
from login1app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('port','profi')

login1/login1app/views.py
from django.shortcuts import render
from login1app.forms import UserForm,UserProfileInfoForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
# Create your views here.

def index(request):
    return render(request,'login1app/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in ")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        use_form = UserForm(data=request.POST)
        pro_form = UserProfileInfoForm(data=request.POST)
        if use_form.is_valid() and pro_form.is_valid():
            user= use_form.save()
            user.set_password(user.password)
            user.save()

            profile=pro_form.save(commit=False)
            profile.user=user

            registered=True

        else:
            print(use_form.errors,pro_form.errors)
    else:
        use_form=UserForm()
        pro_form=UserProfileInfoForm()
    return render(request,'login1app/register.html',{'use_form':use_form,'pro_form':pro_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username='username',password='password')
        if user:
            if user.is_active():
                login(request,user)
                HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("not actibe")

        else:
            print("not a user")
            print("geting detiLS")
            print(username,password)
    else:
        return render(request,'login1app/login.html',{})

login1/templates/login1app/basic.html
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8">
<title>Title hai</title>
</head>
<body>
    <p>this is html</p>
    <h1>printt</h1>

    <a href="{% url 'admin:index' %}">adminss</a>
    <a href="{% url 'login1app:register' %}">registerpage</a>

    {% if user.is_authenticated %}
       <a href="{% url 'user_logout' %}">logoutt</a>
       {% else %}
           <a href="{% url 'user_login' %}">Loginkarle</a>
    {% endif %}
    {% block body_block %}
    {% endblock %}

</body>
  </html>

login1/templates/login1app/index.html
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8">
<title>Title hai</title>
</head>

{% extends "login1app/basic.html" %}
{% block body_block %}
<h1>main page</h1>
<h1>you are welcome here</h1>
{% endblock %}

login1/templates/login1app/login.html
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8">
<title>Title hai</title>
</head>
{% extends "login1app/basic.html" %}
{% block body_block %}
<h1>login form</h1>
<form action="post" action="{% url 'login1app:user_login' %}">
  {% csrf_token %}
  <label for="username">userr</label>
  <input type="text" name="user" placeholder="ent name">

  <label for="password">passwword</label>
  <input type="password" name="pass">

  <input type="submit" name="sub" value="submittt">
</form>



{% endblock %}

login1/templates/login1app/register.html
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8">
<title>Title hai</title>
</head>
{% extends "login1app/basic.html" %}
{% block body_block %}
<h1>registration page</h1>
  {% if registered %}
  <h1>Thanks</h1>
  {% else %}
  <p>register<p>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{use_form.as_p}}
    {{pro_form.as_p}}
  <input type="submit" value="done">
  </form>

  {% endif %}
{% endblock %}